# -*- coding: utf-8 -*-
"""Data Analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10rDawh9ZYLWMjq7V7SYaCeR9NtPbvWLe
"""

!pip install textstat

!pip install scikit-learn
!pip install scipy
!pip install nltk
!pip install seaborn

# prompt: load csv using pandas

import pandas as pd
import csv
question_df = pd.read_csv("vw_jw_question_cycle_1.csv")

log_df = pd.read_csv("vw_log_cycle_1.csv")

question_df.head()

question_df['user_id'].value_counts().plot.bar()

log_df['user_id'].value_counts().plot.bar()

log_df['project_id'].value_counts().plot.bar()

len(question_df['user_id'].value_counts())

len(log_df['user_id'].value_counts())

common_students = list(set(question_df['user_id']) & set(log_df['user_id']))

question_subset = question_df.loc[question_df['user_id'].isin(common_students)]

log_subset = log_df.loc[log_df['user_id'].isin(common_students)]

len(log_subset['user_id'].value_counts())

len(common_students)

sorted_log_subset = log_subset.sort_values(by=['user_id'], ascending=[True])

sorted_question_subset = question_subset.sort_values(by=['user_id'], ascending=[True])

sorted_question_subset['user_id'].value_counts()[1]

sorted_question_subset['user_id'].value_counts().corr(sorted_log_subset['user_id'].value_counts())

